repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: /py\.typed$
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-added-large-files
        args: [--maxkb=1000, --enforce-all]
      - id: detect-private-key
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo-fmt
        entry: just rust-fmt-check
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: cargo-clippy
        name: cargo-clippy
        entry: just rust-lint
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: ruff-format
        name: ruff-format
        entry: just py-format-check
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: ruff-lint
        name: ruff-lint
        entry: just py-lint
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: pyrefly
        name: pyrefly
        entry: just py-types
        language: system
        pass_filenames: false
        stages: [pre-commit]
