[package]
name = "treams-py"
publish = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
authors.workspace = true
readme = "README.md"
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
name = "_native"
crate-type = [ "cdylib" ]

[dependencies]
faer.workspace = true
rayon.workspace = true
nalgebra.workspace = true
treams-core.workspace = true
num-complex.workspace = true
numpy.workspace = true
pyo3.workspace = true

[features]
extension-module = [ "pyo3/extension-module" ]

[lints]
workspace = true
