[package]
name = "treams-py"
publish = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true

[lib]
name = "_native"
crate-type = ["cdylib"]

[dependencies]
faer.workspace = true
rayon.workspace = true
nalgebra.workspace = true
treams-core.workspace = true
num-complex.workspace = true
numpy.workspace = true
pyo3.workspace = true
treams-cuda = { path = "../treams-cuda", optional = true, features = ["cuda"] }
treams-cuda-tile = { path = "../treams-cuda-tile", optional = true, features = ["cuda-tile"] }

[features]
extension-module = ["pyo3/extension-module"]
cuda = ["dep:treams-cuda"]
cuda-tile = ["cuda", "dep:treams-cuda-tile"]

[lints]
workspace = true
