"""T-matrix scattering with a Rust numerical core and native pullbacks."""

from . import coeffs, config, cw, diff, ebcm, iterative, lattice, misc, pw, special, sw
from ._array import PhysicsArray
from ._core import (
    CylindricalWaveBasis,
    Material,
    PlaneWaveBasisByComp,
    PlaneWaveBasisByUnitVector,
    SphericalWaveBasis,
)
from ._lattice import Lattice, WaveVector
from ._operators import (
    BField,
    ChangePoltype,
    DField,
    EField,
    Expand,
    ExpandLattice,
    FField,
    FieldOperator,
    GField,
    HField,
    Operator,
    OperatorAttribute,
    Permute,
    Rotate,
    Translate,
    bfield,
    changepoltype,
    dfield,
    efield,
    expand,
    expandlattice,
    ffield,
    gfield,
    hfield,
    permute,
    rotate,
    translate,
)
from ._plane import PlaneWave, plane_wave, plane_wave_angle
from ._smatrix import SMatrices, SMatrix, chirality_density, poynting_avg_z
from ._source import MultipoleWave, cylindrical_wave, spherical_wave
from ._tmatrix import TMatrix, TMatrixC

__all__ = [
    "BField",
    "ChangePoltype",
    "CylindricalWaveBasis",
    "DField",
    "EField",
    "Expand",
    "ExpandLattice",
    "FField",
    "FieldOperator",
    "GField",
    "HField",
    "Lattice",
    "Material",
    "MultipoleWave",
    "Operator",
    "OperatorAttribute",
    "Permute",
    "PhysicsArray",
    "PlaneWave",
    "PlaneWaveBasisByComp",
    "PlaneWaveBasisByUnitVector",
    "Rotate",
    "SMatrices",
    "SMatrix",
    "SphericalWaveBasis",
    "TMatrix",
    "TMatrixC",
    "Translate",
    "WaveVector",
    "bfield",
    "changepoltype",
    "chirality_density",
    "coeffs",
    "config",
    "cw",
    "cylindrical_wave",
    "dfield",
    "diff",
    "ebcm",
    "efield",
    "expand",
    "expandlattice",
    "ffield",
    "gfield",
    "hfield",
    "iterative",
    "lattice",
    "misc",
    "permute",
    "plane_wave",
    "plane_wave_angle",
    "poynting_avg_z",
    "pw",
    "rotate",
    "special",
    "spherical_wave",
    "sw",
    "translate",
]
