-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [treams_core]: external functions.
-- Definitions for the external functions.
module
public import Aeneas
public import VisitCube.Types
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open treams_core

/-- Array `into_iter`: iterate the elements front to back. -/
def Array.Insts.CoreIterTraitsCollectIntoIteratorTIntoIter.into_iter
  {T : Type} {N : Std.Usize} (a : Array T N) : Result (core.array.iter.IntoIter T N) :=
  ok a.val

/-- Array iterator `next`. -/
def core.array.iter.IntoIter.Insts.CoreIterTraitsIteratorIterator.next
  {T : Type} {N : Std.Usize} (it : core.array.iter.IntoIter T N) :
  Result ((Option T) × (core.array.iter.IntoIter T N)) :=
  match (it : List T) with
  | [] => ok (none, ([] : List T))
  | x :: xs => ok (some x, xs)

/-- `i64::abs`, which panics on `i64::MIN` because overflow checks are enabled. -/
def core.num.I64.abs (x : Std.I64) : Result Std.I64 :=
  if x.val < 0 then -. x else ok x

/-- `RangeInclusive::contains`: `start <= x` and `x <= end`, or `x < end` once exhausted. -/
def core.ops.range.RangeInclusive.contains
  {Idx : Type} {U : Type} (cmpPartialOrdInst : core.cmp.PartialOrd Idx Idx)
  (cmpPartialOrdInst1 : core.cmp.PartialOrd Idx U) (cmpPartialOrdInst2 :
  core.cmp.PartialOrd U Idx) (r : core.ops.range.RangeInclusive Idx) (x : U) :
  Result Bool := do
  let lower ← cmpPartialOrdInst1.le r.start x
  let upper ← if r.exhausted then cmpPartialOrdInst2.lt x r.«end»
    else cmpPartialOrdInst2.le x r.«end»
  ok (lower && upper)

/-- `String::from(&str)`, decoding one character per byte; the messages are ASCII. -/
def alloc.string.String.Insts.CoreConvertFromShared0Str.from (s : Str) : Result String :=
  ok (String.ofList (s.val.map fun b => Char.ofNat b.val))
