-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [treams_core]: function definitions
module
public import Aeneas
public import VisitCube.Types
public import VisitCube.FunsExternal
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace treams_core

/-- Trait implementation: [alloc::string::{impl core::convert::From<&'_0 str> for alloc::string::String}]
    Source: '/rustc/library/alloc/src/string.rs', lines 3180:0-3180:26
    Name pattern: [core::convert::From<alloc::string::String, &'0 str>] -/
@[reducible, rust_trait_impl
  "core::convert::From<alloc::string::String, &'0 str>"]
def alloc.string.String.Insts.CoreConvertFromShared0Str : core.convert.From
  String Str := {
  «from» := alloc.string.String.Insts.CoreConvertFromShared0Str.from
}

mutual

/-- [treams_core::geometry::visit_cube::append]: loop 0:
    Source: 'crates/treams-core/src/geometry.rs', lines 123:12-137:5 -/
@[rust_loop]
def geometry.visit_cube.append_loop0
  {T0 : Type} (coreopsfunctionFnMutT0TupleArrayI643ResultTupleErrorInst :
  core.ops.function.FnMut T0 (Array Std.I64 3#usize) (core.result.Result Unit
  Error)) (iter : core.ops.range.RangeInclusive Std.I64)
  (point : Array Std.I64 3#usize) (dim : Std.Usize) (axis : Std.Usize)
  (n : Std.I64) (visitor : T0) :
  Result ((core.result.Result Unit Error) × (Array Std.I64 3#usize) × T0)
  := do
  let (o, iter1) ←
    core.ops.range.RangeInclusive.Insts.CoreIterTraitsIteratorIterator.next
      core.iter.range.StepI64 iter
  match o with
  | none => ok (core.result.Result.Ok (), point, visitor)
  | some value =>
    let point1 ← Array.update point axis value
    let i ← axis + 1#usize
    let (r, point2, visitor1) ←
      geometry.visit_cube.append
        coreopsfunctionFnMutT0TupleArrayI643ResultTupleErrorInst point1 dim i n
        true true visitor
    let cf ← core.result.Result.Insts.CoreOpsTry.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue _ =>
      geometry.visit_cube.append_loop0
        coreopsfunctionFnMutT0TupleArrayI643ResultTupleErrorInst iter1 point2
        dim axis n visitor1
    | core.ops.control_flow.ControlFlow.Break residual =>
      let r1 ←
        core.result.Result.Insts.CoreOpsTry_traitFromResidualResult.from_residual
          Unit (core.convert.FromSame Error) residual
      ok (r1, point2, visitor1)
partial_fixpoint

/-- [treams_core::geometry::visit_cube::append]: loop 1:
    Source: 'crates/treams-core/src/geometry.rs', lines 118:12-137:5 -/
@[rust_loop]
def geometry.visit_cube.append_loop1
  {T0 : Type} (coreopsfunctionFnMutT0TupleArrayI643ResultTupleErrorInst :
  core.ops.function.FnMut T0 (Array Std.I64 3#usize) (core.result.Result Unit
  Error)) (iter : core.array.iter.IntoIter Std.I64 2#usize)
  (point : Array Std.I64 3#usize) (dim : Std.Usize) (axis : Std.Usize)
  (n : Std.I64) (visitor : T0) :
  Result ((core.result.Result Unit Error) × (Array Std.I64 3#usize) × T0)
  := do
  let (o, iter1) ←
    core.array.iter.IntoIter.Insts.CoreIterTraitsIteratorIterator.next iter
  match o with
  | none => ok (core.result.Result.Ok (), point, visitor)
  | some value =>
    let point1 ← Array.update point axis value
    let i ← axis + 1#usize
    let (r, point2, visitor1) ←
      geometry.visit_cube.append
        coreopsfunctionFnMutT0TupleArrayI643ResultTupleErrorInst point1 dim i n
        true true visitor
    let cf ← core.result.Result.Insts.CoreOpsTry.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue _ =>
      geometry.visit_cube.append_loop1
        coreopsfunctionFnMutT0TupleArrayI643ResultTupleErrorInst iter1 point2
        dim axis n visitor1
    | core.ops.control_flow.ControlFlow.Break residual =>
      let r1 ←
        core.result.Result.Insts.CoreOpsTry_traitFromResidualResult.from_residual
          Unit (core.convert.FromSame Error) residual
      ok (r1, point2, visitor1)
partial_fixpoint

/-- [treams_core::geometry::visit_cube::append]: loop 2:
    Source: 'crates/treams-core/src/geometry.rs', lines 123:12-137:5 -/
@[rust_loop]
def geometry.visit_cube.append_loop2
  {T0 : Type} (coreopsfunctionFnMutT0TupleArrayI643ResultTupleErrorInst :
  core.ops.function.FnMut T0 (Array Std.I64 3#usize) (core.result.Result Unit
  Error)) (iter : core.ops.range.RangeInclusive Std.I64)
  (point : Array Std.I64 3#usize) (dim : Std.Usize) (axis : Std.Usize)
  (n : Std.I64) (visitor : T0) :
  Result ((core.result.Result Unit Error) × (Array Std.I64 3#usize) × T0)
  := do
  let (o, iter1) ←
    core.ops.range.RangeInclusive.Insts.CoreIterTraitsIteratorIterator.next
      core.iter.range.StepI64 iter
  match o with
  | none => ok (core.result.Result.Ok (), point, visitor)
  | some value =>
    let point1 ← Array.update point axis value
    let i ← axis + 1#usize
    let i1 ← core.num.I64.abs value
    let (r, point2, visitor1) ←
      geometry.visit_cube.append
        coreopsfunctionFnMutT0TupleArrayI643ResultTupleErrorInst point1 dim i n
        true (i1 = n) visitor
    let cf ← core.result.Result.Insts.CoreOpsTry.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue _ =>
      geometry.visit_cube.append_loop2
        coreopsfunctionFnMutT0TupleArrayI643ResultTupleErrorInst iter1 point2
        dim axis n visitor1
    | core.ops.control_flow.ControlFlow.Break residual =>
      let r1 ←
        core.result.Result.Insts.CoreOpsTry_traitFromResidualResult.from_residual
          Unit (core.convert.FromSame Error) residual
      ok (r1, point2, visitor1)
partial_fixpoint

/-- [treams_core::geometry::visit_cube::append]: loop 3:
    Source: 'crates/treams-core/src/geometry.rs', lines 123:12-137:5 -/
@[rust_loop]
def geometry.visit_cube.append_loop3
  {T0 : Type} (coreopsfunctionFnMutT0TupleArrayI643ResultTupleErrorInst :
  core.ops.function.FnMut T0 (Array Std.I64 3#usize) (core.result.Result Unit
  Error)) (iter : core.ops.range.RangeInclusive Std.I64)
  (point : Array Std.I64 3#usize) (dim : Std.Usize) (axis : Std.Usize)
  (n : Std.I64) (visitor : T0) :
  Result ((core.result.Result Unit Error) × (Array Std.I64 3#usize) × T0)
  := do
  let (o, iter1) ←
    core.ops.range.RangeInclusive.Insts.CoreIterTraitsIteratorIterator.next
      core.iter.range.StepI64 iter
  match o with
  | none => ok (core.result.Result.Ok (), point, visitor)
  | some value =>
    let point1 ← Array.update point axis value
    let i ← axis + 1#usize
    let i1 ← core.num.I64.abs value
    let (r, point2, visitor1) ←
      geometry.visit_cube.append
        coreopsfunctionFnMutT0TupleArrayI643ResultTupleErrorInst point1 dim i n
        true (i1 = n) visitor
    let cf ← core.result.Result.Insts.CoreOpsTry.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue _ =>
      geometry.visit_cube.append_loop3
        coreopsfunctionFnMutT0TupleArrayI643ResultTupleErrorInst iter1 point2
        dim axis n visitor1
    | core.ops.control_flow.ControlFlow.Break residual =>
      let r1 ←
        core.result.Result.Insts.CoreOpsTry_traitFromResidualResult.from_residual
          Unit (core.convert.FromSame Error) residual
      ok (r1, point2, visitor1)
partial_fixpoint

/-- [treams_core::geometry::visit_cube::append]: loop 4:
    Source: 'crates/treams-core/src/geometry.rs', lines 123:12-137:5 -/
@[rust_loop]
def geometry.visit_cube.append_loop4
  {T0 : Type} (coreopsfunctionFnMutT0TupleArrayI643ResultTupleErrorInst :
  core.ops.function.FnMut T0 (Array Std.I64 3#usize) (core.result.Result Unit
  Error)) (iter : core.ops.range.RangeInclusive Std.I64)
  (point : Array Std.I64 3#usize) (dim : Std.Usize) (axis : Std.Usize)
  (n : Std.I64) (boundary : Bool) (visitor : T0) :
  Result ((core.result.Result Unit Error) × (Array Std.I64 3#usize) × T0)
  := do
  let (o, iter1) ←
    core.ops.range.RangeInclusive.Insts.CoreIterTraitsIteratorIterator.next
      core.iter.range.StepI64 iter
  match o with
  | none => ok (core.result.Result.Ok (), point, visitor)
  | some value =>
    let point1 ← Array.update point axis value
    let i ← axis + 1#usize
    if boundary
    then
      let (r, point2, visitor1) ←
        geometry.visit_cube.append
          coreopsfunctionFnMutT0TupleArrayI643ResultTupleErrorInst point1 dim i
          n false true visitor
      let cf ← core.result.Result.Insts.CoreOpsTry.branch r
      match cf with
      | core.ops.control_flow.ControlFlow.Continue _ =>
        geometry.visit_cube.append_loop4
          coreopsfunctionFnMutT0TupleArrayI643ResultTupleErrorInst iter1 point2
          dim axis n true visitor1
      | core.ops.control_flow.ControlFlow.Break residual =>
        let r1 ←
          core.result.Result.Insts.CoreOpsTry_traitFromResidualResult.from_residual
            Unit (core.convert.FromSame Error) residual
        ok (r1, point2, visitor1)
    else
      let i1 ← core.num.I64.abs value
      let (r, point2, visitor1) ←
        geometry.visit_cube.append
          coreopsfunctionFnMutT0TupleArrayI643ResultTupleErrorInst point1 dim i
          n false (i1 = n) visitor
      let cf ← core.result.Result.Insts.CoreOpsTry.branch r
      match cf with
      | core.ops.control_flow.ControlFlow.Continue _ =>
        geometry.visit_cube.append_loop4
          coreopsfunctionFnMutT0TupleArrayI643ResultTupleErrorInst iter1 point2
          dim axis n false visitor1
      | core.ops.control_flow.ControlFlow.Break residual =>
        let r1 ←
          core.result.Result.Insts.CoreOpsTry_traitFromResidualResult.from_residual
            Unit (core.convert.FromSame Error) residual
        ok (r1, point2, visitor1)
partial_fixpoint

/-- [treams_core::geometry::visit_cube::append]:
    Source: 'crates/treams-core/src/geometry.rs', lines 105:4-137:5 -/
def geometry.visit_cube.append
  {T0 : Type} (coreopsfunctionFnMutT0TupleArrayI643ResultTupleErrorInst :
  core.ops.function.FnMut T0 (Array Std.I64 3#usize) (core.result.Result Unit
  Error)) (point : Array Std.I64 3#usize) (dim : Std.Usize) (axis : Std.Usize)
  (n : Std.I64) (edge : Bool) (boundary : Bool) (visitor : T0) :
  Result ((core.result.Result Unit Error) × (Array Std.I64 3#usize) × T0)
  := do
  if axis = dim
  then
    let (r, visitor1) ←
      coreopsfunctionFnMutT0TupleArrayI643ResultTupleErrorInst.call_mut visitor
        point
    ok (r, point, visitor1)
  else
    if edge
    then
      if boundary
      then
        let i ← -. n
        let iter ← core.ops.range.RangeInclusive.new i n
        geometry.visit_cube.append_loop0
          coreopsfunctionFnMutT0TupleArrayI643ResultTupleErrorInst iter point
          dim axis n visitor
      else
        let i ← axis + 1#usize
        if i = dim
        then
          if n > 0#i64
          then
            let i1 ← -. n
            let iter ←
              Array.Insts.CoreIterTraitsCollectIntoIteratorTIntoIter.into_iter
                (Array.make 2#usize [ i1, n ])
            geometry.visit_cube.append_loop1
              coreopsfunctionFnMutT0TupleArrayI643ResultTupleErrorInst iter
              point dim axis n visitor
          else
            let i1 ← -. n
            let iter ← core.ops.range.RangeInclusive.new i1 n
            geometry.visit_cube.append_loop2
              coreopsfunctionFnMutT0TupleArrayI643ResultTupleErrorInst iter
              point dim axis n visitor
        else
          let i1 ← -. n
          let iter ← core.ops.range.RangeInclusive.new i1 n
          geometry.visit_cube.append_loop3
            coreopsfunctionFnMutT0TupleArrayI643ResultTupleErrorInst iter point
            dim axis n visitor
    else
      let i ← -. n
      let iter ← core.ops.range.RangeInclusive.new i n
      geometry.visit_cube.append_loop4
        coreopsfunctionFnMutT0TupleArrayI643ResultTupleErrorInst iter point dim
        axis n boundary visitor
partial_fixpoint

end

/-- [treams_core::geometry::visit_cube]:
    Source: 'crates/treams-core/src/geometry.rs', lines 94:0-139:1 -/
def geometry.visit_cube
  {T0 : Type} (coreopsfunctionFnMutT0TupleArrayI643ResultTupleErrorInst :
  core.ops.function.FnMut T0 (Array Std.I64 3#usize) (core.result.Result Unit
  Error)) (dim : Std.Usize) (n : Std.I64) (edge : Bool) (visitor : T0) :
  Result (core.result.Result Unit Error)
  := do
  let ri ← core.ops.range.RangeInclusive.new 1#usize 3#usize
  let b ←
    core.ops.range.RangeInclusive.contains core.cmp.PartialOrdUsize
      core.cmp.PartialOrdUsize core.cmp.PartialOrdUsize ri dim
  if b
  then
    if n < 0#i64
    then
      let s ←
        core.convert.IntoFrom.into
          alloc.string.String.Insts.CoreConvertFromShared0Str (toStr
          "cube requires dimension 1, 2 or 3 and nonnegative size")
      ok (core.result.Result.Err (Error.InvalidInput s))
    else
      let a := Array.repeat 3#usize 0#i64
      let (r, _, _) ←
        geometry.visit_cube.append
          coreopsfunctionFnMutT0TupleArrayI643ResultTupleErrorInst a dim
          0#usize n edge false visitor
      ok r
  else
    let s ←
      core.convert.IntoFrom.into
        alloc.string.String.Insts.CoreConvertFromShared0Str (toStr
        "cube requires dimension 1, 2 or 3 and nonnegative size")
    ok (core.result.Result.Err (Error.InvalidInput s))

end treams_core
