-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [treams_core]: type definitions
module
public import Aeneas
public import VisitCube.TypesExternal
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace treams_core

/-- [treams_core::Error]
    Source: 'crates/treams-core/src/lib.rs', lines 60:0-70:1
    Visibility: public -/
@[discriminant isize]
inductive Error where
| InvalidInput : String → Error
| SpecialFunction : String → Error
| Singular : Error

end treams_core
