-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [treams_core]: external types.
-- Definitions for the external types.
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/-- Remaining elements of an array iterator, front first. -/
@[rust_type "core::array::iter::IntoIter"]
def core.array.iter.IntoIter (T : Type) (N : Std.Usize) : Type := List T
