# /// script
# requires-python = ">=3.12,<3.14"
# ///
"""Generate or check the Python API reference, the generated regions and llms.txt.

Run ``python scripts/generate_docs.py`` to write the files and ``--check`` to
fail when any of them differs from its source:

* ``docs/reference/python/``: an index, one page per public module and a page
  of returned types, rendered from ``treams_rs.support_catalog()``.
* Generated regions of hand-written pages. A page asks for one with
  ``<!-- generated: NAME -->`` followed by ``<!-- end generated -->``; the
  generator replaces the lines between them. ``upstream-names`` is the treams
  name map, and ``rust-crosswalk`` is the module table of the treams-core
  crate docs (between ``<!-- crosswalk:start -->`` and
  ``<!-- crosswalk:end -->`` in ``crates/treams-core/src/lib.rs``).
* ``llms.txt``: every page of the mkdocs.yml nav with its front-matter
  description.

The mkdocs.yml nav is the one list of documentation pages: the check also fails
when a page is missing from the nav, a nav entry has no file, or a page has no
description.

``--examples`` runs every ``docs/examples/*.py`` script and writes what it
prints to ``docs/examples/output/<name>.txt``. ``--check`` leaves these files
alone: ``tests/api/test_examples.py`` compares them with a fresh run.
"""

import argparse
import inspect
import re
import subprocess
import sys
from collections.abc import Callable
from pathlib import Path
from typing import Any

import yaml

import treams_rs
from treams_rs._catalog import (
    docstring_markdown,
    render_markdown,
    render_overview,
    render_returned_types,
    support_catalog,
)

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
REFERENCE = "reference/python/"
CRATE_DOCS = ROOT / "crates/treams-core/src/lib.rs"
EXAMPLES = DOCS / "examples"
# ruff formats python fences in Markdown; "fmt: off" keeps the docstring code
# of the reference pages exactly as the docstrings write it.
NOTICE = (
    "<!-- Generated by scripts/generate_docs.py from the docstrings;"
    " run `just docs` after editing them. -->\n<!-- fmt: off -->"
)
# Site machinery under docs/, not pages.
NOT_PAGES = ("_hooks/",)
FRONT_MATTER = re.compile(r"\A---\n(?P<yaml>.*?)\n---\n", re.S)
LINK = re.compile(r"\]\((?P<target>[^)\s]+)\)")
REGION = re.compile(
    r"(?P<start><!-- generated: (?P<name>[\w-]+) -->\n)(?P<body>.*?)"
    r"(?P<end><!-- end generated -->)",
    re.S,
)
CROSSWALK = re.compile(
    r"^//! ?<!-- crosswalk:start -->\n(?P<table>.*?)^//! ?<!-- crosswalk:end -->",
    re.S | re.M,
)
# An intra-doc link [`name`] or [`name`][target], but not a Markdown [`name`](url).
INTRA_DOC_LINK = re.compile(r"\[(`[^`]+`)\](?:\[[^\]]*\])?(?!\()")


def _site() -> dict:
    return yaml.safe_load((ROOT / "mkdocs.yml").read_text(encoding="utf-8"))


def _page_source(page: str, generated: dict[Path, str] | None = None) -> str:
    path = DOCS / page
    if generated is not None and path in generated:
        return generated[path]
    return path.read_text(encoding="utf-8") if path.is_file() else ""


def _front_matter(page: str, generated: dict[Path, str] | None = None) -> dict:
    match = FRONT_MATTER.match(_page_source(page, generated))
    return (yaml.safe_load(match["yaml"]) or {}) if match else {}


def _heading(page: str, generated: dict[Path, str] | None = None) -> str | None:
    text = FRONT_MATTER.sub("", _page_source(page, generated), count=1)
    match = re.search(r"^# (.+)$", text, re.M)
    return match[1].strip() if match else None


def nav_pages(generated: dict[Path, str] | None = None) -> list[tuple[str, str, str]]:
    """``(section, title, path)`` of every nav page, in nav order.

    The title is the nav label, else the page's first H1. A top-level page
    forms its own section, named by its label; pages of a nested list belong
    to their top-level section.
    """
    pages = []

    def walk(entries: list, section: str | None) -> None:
        for entry in entries:
            label, value = (
                next(iter(entry.items())) if isinstance(entry, dict) else (None, entry)
            )
            if isinstance(value, list):
                walk(value, section or label)
                continue
            heading = _heading(value, generated)
            title = label or heading or value
            pages.append((section or title, title, value))

    walk(_site()["nav"], None)
    return pages


def _llms(version: str, generated: dict[Path, str] | None = None) -> str:
    lines = [
        "# treams-rs",
        "",
        "> A Rust port of treams for electromagnetic T-matrix scattering, with a"
        f" Python interface and analytic first-order gradients. Version {version}.",
        "",
        f"The documentation site is {_site()['site_url']}.",
        "The Markdown sources linked below are in this repository, at the same Git"
        " revision as this file.",
        "After installing the package, run `python -m treams_rs` for a short example,",
        "`python -m treams_rs sphere_tmatrix` for one function, or `--search TEXT`"
        " to find names.",
        "Use `--format json` or `--format markdown` to list all documented functions"
        " and classes.",
        "`treams_rs.support_catalog()` never imports optional frameworks.",
    ]
    section = None
    for name, title, page in nav_pages(generated):
        if name != section:
            lines += ["", f"## {name}", ""]
            section = name
        description = _front_matter(page, generated).get("description", "")
        lines.append(f"- [{title}](docs/{page}): {description}")
    return "\n".join([*lines, ""])


def index_errors() -> list[str]:
    """Every nav page exists, every page is in the nav with a description, and
    every llms.txt link resolves.

    Pages under ``docs/reference/python/`` count as present: the generator
    writes them, with their descriptions, after this check.
    """
    nav = [page for _, _, page in nav_pages()]
    missing = [
        page
        for page in nav
        if not page.startswith(REFERENCE) and not (DOCS / page).is_file()
    ]
    pages = {
        page
        for page in (path.relative_to(DOCS).as_posix() for path in DOCS.rglob("*.md"))
        if not page.startswith(NOT_PAGES)
    }
    undescribed = [
        page
        for page in sorted(pages)
        if not page.startswith(REFERENCE) and not _front_matter(page).get("description")
    ]
    links = [match["target"] for match in LINK.finditer(_llms("0"))]
    return (
        [f"docs/{page} is in the mkdocs.yml nav but does not exist" for page in missing]
        + [
            f"docs/{page} is not in the mkdocs.yml nav"
            for page in sorted(pages - set(nav))
        ]
        + [f"docs/{page} has no front-matter description" for page in undescribed]
        + [
            f"llms.txt links to the missing file {target}"
            for target in links
            if not target.startswith(f"docs/{REFERENCE}")
            and not (ROOT / target).is_file()
        ]
    )


def _first_sentence(doc: str) -> str:
    paragraph = " ".join(doc.partition("\n\n")[0].split())
    match = re.match(r"(.+?\.)(?:\s|$)", paragraph)
    return match[1] if match else paragraph


def _page_name(module: str) -> str:
    """``treams_rs`` for the package root, else the submodule name."""
    return module if module == "treams_rs" else module.rpartition(".")[2]


def _page(description: str, title: str, body: str) -> str:
    front_matter = yaml.safe_dump(
        {"description": description}, allow_unicode=True, width=1000
    )
    # MkDocs takes the page title from an H1 only when it is the first element.
    return f"---\n{front_matter}---\n\n# {title}\n\n{NOTICE}\n\n{body.rstrip()}\n"


def _cell(text: str) -> str:
    return text.replace("|", "\\|")


def upstream_names(catalog: dict[str, Any]) -> str:
    """Markdown tables of the treams names that treams-rs spells differently."""
    upstream = catalog["upstream"]
    lines = [
        "## treams top-level names",
        "",
        "| treams | treams-rs | Note |",
        "| --- | --- | --- |",
    ]
    for name, renamed in upstream["names"].items():
        target = f"`treams_rs.{renamed['target']}`" if renamed["target"] else "none"
        lines.append(f"| `treams.{name}` | {target} | {_cell(renamed['note'])} |")
    tables = [("members", "Members of treams objects", "Class", "treams member")]
    if "keywords" in upstream:
        tables.append(("keywords", "Keywords", "Function", "treams keyword"))
    for key, heading, owner_column, name_column in tables:
        lines.extend(
            [
                "",
                f"## {heading}",
                "",
                f"| {owner_column} | {name_column} | treams-rs name or note |",
                "| --- | --- | --- |",
            ]
        )
        for owner, members in upstream[key].items():
            for name, renamed in members.items():
                target = f"`{renamed['target']}`." if renamed["target"] else ""
                cell = " ".join(filter(None, (target, _cell(renamed["note"]))))
                lines.append(f"| `{owner}` | `{name}` | {cell} |")
    return "\n".join(lines) + "\n"


def rust_crosswalk(source: str) -> str:
    """The crosswalk table of the treams-core crate docs as plain Markdown.

    Raises:
        ValueError: ``source`` has no crosswalk markers.
    """
    match = CROSSWALK.search(source)
    if match is None:
        raise ValueError(
            "the treams-core crate docs have no <!-- crosswalk:start --> table"
        )
    lines = [
        line.removeprefix("//!").removeprefix(" ")
        for line in match["table"].splitlines()
    ]
    return "\n".join(INTRA_DOC_LINK.sub(r"\1", line) for line in lines) + "\n"


def fill_regions(text: str, regions: dict[str, Callable[[], str]]) -> str:
    """``text`` with every generated region replaced by its current content.

    Raises:
        ValueError: a region names no known generator.
    """

    def fill(match: re.Match[str]) -> str:
        generate = regions.get(match["name"])
        if generate is None:
            raise ValueError(f"unknown generated region {match['name']!r}")
        return f"{match['start']}\n{generate().rstrip()}\n\n{match['end']}"

    return REGION.sub(fill, text)


def reference_pages(catalog: dict[str, Any]) -> dict[Path, str]:
    """The index, one page per public module and the page of returned types.

    Module pages follow the order of the mkdocs.yml nav.
    """
    root_doc = inspect.cleandoc(treams_rs.__doc__ or "")
    docs = {"treams_rs": root_doc, **catalog["modules"]}
    order = {page: index for index, (_, _, page) in enumerate(nav_pages())}
    modules = sorted(
        docs,
        key=lambda module: (
            order.get(f"{REFERENCE}{_page_name(module)}.md", len(order)),
            module,
        ),
    )
    pages: dict[Path, str] = {}
    for module in modules:
        body = render_markdown(catalog, module=module)
        if module == "treams_rs":
            body = docstring_markdown(root_doc) + "\n\n" + body
        pages[DOCS / REFERENCE / f"{_page_name(module)}.md"] = _page(
            _first_sentence(docs[module]), f"`{module}`", body
        )
    table = ["| Module | Summary |", "| --- | --- |"]
    table.extend(
        f"| [`{module}`]({_page_name(module)}.md) "
        f"| {_cell(_first_sentence(docs[module]))} |"
        for module in modules
    )
    index = "\n".join(
        [
            "Each public module of `treams_rs` has one page with the signature and",
            "docstring of every name it exports. Classes list their methods and",
            "attributes, including those inherited from other treams-rs classes.",
            "",
            "A **Pullback** line names the method of the returned context that",
            "turns the gradient of a real loss with respect to the output into",
            "gradients with respect to the inputs (see the",
            "[glossary](../glossary.md)).",
            "",
            *table,
            "",
            "[Returned types](native-types.md) lists the objects that records and",
            "solvers return.",
            "",
            render_overview(catalog),
        ]
    )
    pages[DOCS / REFERENCE / "index.md"] = _page(
        "Every public module of treams_rs, with signatures and docstrings generated"
        " from the source.",
        "Python API",
        index,
    )
    pages[DOCS / REFERENCE / "native-types.md"] = _page(
        "Objects that public records and solvers return: native contexts and"
        " factors, and Python helper objects.",
        "Returned types",
        render_returned_types(catalog),
    )
    return pages


def generated_files() -> dict[Path, str]:
    """Every generated file with its current content."""
    catalog = support_catalog()
    regions = {
        "upstream-names": lambda: upstream_names(catalog),
        "rust-crosswalk": lambda: rust_crosswalk(
            CRATE_DOCS.read_text(encoding="utf-8")
        ),
    }
    files = reference_pages(catalog)
    for path in sorted(DOCS.rglob("*.md")):
        text = path.read_text(encoding="utf-8")
        if path not in files and REGION.search(text):
            files[path] = fill_regions(text, regions)
    files[ROOT / "llms.txt"] = _llms(catalog["version"], files)
    return files


def stale_files(files: dict[Path, str]) -> list[Path]:
    """The paths whose content on disk differs from ``files``."""
    return [
        path
        for path, content in files.items()
        if not path.is_file() or path.read_text(encoding="utf-8") != content
    ]


def orphan_pages(files: dict[Path, str]) -> list[Path]:
    """Reference pages on disk that no module generates any more."""
    return sorted(page for page in (DOCS / REFERENCE).glob("*.md") if page not in files)


def write_example_outputs() -> None:
    """Run every gallery script from the repository root; record what it prints."""
    for script in sorted(EXAMPLES.glob("*.py")):
        printed = subprocess.run(
            [sys.executable, str(script)],
            cwd=ROOT,
            check=True,
            stdout=subprocess.PIPE,
            text=True,
        ).stdout
        output = EXAMPLES / "output" / f"{script.stem}.txt"
        output.parent.mkdir(exist_ok=True)
        output.write_text(printed, encoding="utf-8")
        print(f"Wrote {output.relative_to(ROOT)}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--examples", action="store_true")
    args = parser.parse_args()
    if args.examples:
        write_example_outputs()
        return
    if errors := index_errors():
        raise SystemExit("documentation pages: " + "; ".join(errors))
    files = generated_files()
    if args.check:
        if stale := stale_files(files) + orphan_pages(files):
            names = ", ".join(str(path.relative_to(ROOT)) for path in stale)
            raise SystemExit(f"stale generated files: {names}; run just docs")
        print("Generated documentation is current")
        return
    # Pages of removed modules go with them.
    for page in orphan_pages(files):
        page.unlink()
    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    print("Generated documentation written")


if __name__ == "__main__":
    main()
